### PR TITLE
Upgrade @jupiterone/data-model@0.6.3

### PR DESCRIPTION
**Pull request by aiwilliams**

### CODE REVIEW

**Comment by charlieduong94** [comment]
Strange, looks like there are some type issues.

**Comment by aiwilliams** [comment]
Yah, weird, https://github.com/JupiterOne/data-model/runs/734964937?check_suite_focus=true shows a very empty data-model package release 😢

**Comment by charlieduong94** [comment]
Once the data model publish is fixed and this PR merged, lets release 1.0.0 of all of the packages.

**Comment by aiwilliams** [comment]
> Once the data model publish is fixed and this PR merged, lets release 1.0.0 of all of the packages.

Sounds great!

**Pull request merged**
