### PR TITLE
Ensure arrays are not too large

### PR DESCRIPTION
**Pull request by mknoedel**
Created in response to - [Google Cloud #288](https://github.com/JupiterOne/graph-google-cloud/pull/288)

Neptune has an undocumented cap of how many array elements it can store in a single edge or vertex. Through some investigation, @softwarewright found this limit to be around 1,500 elements. 

The google cloud integration was sometimes attempting to store permission arrays that were more than 1,500 elements. Those were causing an error in the persister which was not bubbling back to the integration, so these objects were not getting stored.

In order to avoid the confusion, it seems better to add this check in the sdk to catch these issues early.

This check was only added to entities because the persister handles array properties differently between Entities and Relationships -- see [Persister #67](https://github.com/JupiterOne/jupiter-persister/pull/67). I am unsure why the persister handles these differently.

### CODE REVIEW

**Review by aiwilliams — COMMENTED** [review]
Would be great to get a CHANGELOG entry alongside these changes.

Is there any chance that it matters how big the entries are in the array? One thing is sure: they [don't document any limits](https://docs.aws.amazon.com/neptune/latest/userguide/limits.html) beyond `55MB` 😆

**Comment by ndowmon** [comment]
> around 1,500 elements

I don't see anything about array length, but I do see the following on AWS docs:

>There is a size limit of 55 MB on the size of an individual property or label. In RDF terms, this means that the value in any column (S, P, O or G) of an RDF quad cannot exceed 55 MB.

https://docs.aws.amazon.com/neptune/latest/userguide/limits.html

Should this PR instead be set up to check the property size?

**Comment by mknoedel** [comment]
To both @ndowmon and @aiwilliams, this was a limit that @softwarewright was seeing in the persister logs. We will have to wait until he gets back from vacation to verify.

**Comment by mknoedel** [comment]
> Would be great to get a CHANGELOG entry alongside these changes.

Oops, `git add .` acts weird when you working in a monorepo, my bad, adding that back in.

**Comment by mknoedel** [comment]
No longer needed.

**Pull request closed without merging**
